import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import Head from "next/head";
import { AuthProvider } from "../Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Attendance App",
  description: "Generated by emea developer app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className={inter.className}>
          <h1 className="text-center font-bold text-lg">Admin Panel</h1>
          <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
